using System;
using System.Linq;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace SpookyGame.Editor
{
    /// <summary>
    /// Converts the read-only clips generated by Unity's Aseprite importer into
    /// editable combat clips and connects them to the shipped enemy prefabs.
    /// </summary>
    [InitializeOnLoad]
    internal static class EnemyAnimationSetup
    {
        private const bool AutoInstallEnabled = false;
        private const string AttackParameter = "Attack";

        private const string PossumWalkSource =
            "Assets/Art/Characters/Mobs/Possum/possum_walk.aseprite";
        private const string PossumAttackSource =
            "Assets/Art/Characters/Mobs/Possum/scratch_animation.aseprite";
        private const string PossumWalkClipPath =
            "Assets/Art/Characters/Mobs/Possum/Possum_Walk.anim";
        private const string PossumAttackClipPath =
            "Assets/Art/Characters/Mobs/Possum/Possum_Scratch.anim";
        private const string PossumControllerPath =
            "Assets/Art/Characters/Mobs/Possum/Possum_Combat.controller";
        private const string PossumPrefabPath = "Assets/Prefabs/Enemies/Possum_Mob.prefab";

        private const string LloronaIdleSource =
            "Assets/Art/Characters/Bosses/Llorona/llorona.aseprite";
        private const string LloronaAttackSource =
            "Assets/Art/Characters/Bosses/Llorona/llorona_animation.aseprite";
        private const string LloronaIdleClipPath =
            "Assets/Art/Characters/Bosses/Llorona/Llorona_Normal_Idle.anim";
        private const string LloronaAttackClipPath =
            "Assets/Art/Characters/Bosses/Llorona/Llorona_Scream_Attack.anim";
        private const string LloronaControllerPath =
            "Assets/Art/Characters/Bosses/Llorona/Llorona_Combat.controller";
        private const string LloronaPrefabPath = "Assets/Prefabs/Villains/Llorona_Boss.prefab";

        static EnemyAnimationSetup()
        {
            if (AutoInstallEnabled)
                EditorApplication.delayCall += Install;
        }

        [MenuItem("Tools/Spooky Game/Rebuild Enemy Combat Animations")]
        private static void Install()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode || EditorApplication.isCompiling)
                return;

            AnimationClip importedPossumWalk = FindLongestClip(PossumWalkSource);
            AnimationClip importedPossumAttack = FindLongestClip(PossumAttackSource);
            Sprite lloronaNormalSprite = FindFirstSprite(LloronaIdleSource);
            AnimationClip importedLloronaAttack = FindLongestClip(LloronaAttackSource);

            if (importedPossumWalk == null || importedPossumAttack == null ||
                lloronaNormalSprite == null || importedLloronaAttack == null)
            {
                Debug.LogWarning("[EnemyAnimationSetup] Waiting for all Aseprite source assets to finish importing.");
                return;
            }

            AnimationClip possumWalk = CloneSpriteClip(importedPossumWalk, PossumWalkClipPath, true);
            AnimationClip possumAttack = CloneSpriteClip(importedPossumAttack, PossumAttackClipPath, false);
            AnimationClip lloronaIdle = CreateSingleSpriteClip(lloronaNormalSprite, LloronaIdleClipPath);
            AnimationClip lloronaAttack = CloneSpriteClip(importedLloronaAttack, LloronaAttackClipPath, false);

            AnimatorController possumController = BuildController(
                PossumControllerPath, "Walk", possumWalk, "Scratch", possumAttack);
            AnimatorController lloronaController = BuildController(
                LloronaControllerPath, "Normal Idle", lloronaIdle, "Scream Attack", lloronaAttack);

            ConfigurePrefab(PossumPrefabPath, possumController, possumAttack, 0.46f, 0.12f);
            ConfigurePrefab(LloronaPrefabPath, lloronaController, lloronaAttack, 0.58f, 0.25f);

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log($"[EnemyAnimationSetup] Installed possum scratch ({possumAttack.length:0.00}s) " +
                      $"and La Llorona scream attack ({lloronaAttack.length:0.00}s) animations.");
        }

        private static AnimationClip FindLongestClip(string assetPath)
        {
            return AssetDatabase.LoadAllAssetsAtPath(assetPath)
                .OfType<AnimationClip>()
                .Where(clip => !clip.name.StartsWith("__preview__", StringComparison.OrdinalIgnoreCase))
                .OrderByDescending(clip => clip.length)
                .FirstOrDefault();
        }

        private static Sprite FindFirstSprite(string assetPath)
        {
            return AssetDatabase.LoadAllAssetsAtPath(assetPath).OfType<Sprite>().FirstOrDefault();
        }

        private static AnimationClip CloneSpriteClip(
            AnimationClip source,
            string destinationPath,
            bool loop)
        {
            EditorCurveBinding sourceBinding = AnimationUtility.GetObjectReferenceCurveBindings(source)
                .Where(binding => binding.type == typeof(SpriteRenderer) && binding.propertyName == "m_Sprite")
                .OrderByDescending(binding =>
                    AnimationUtility.GetObjectReferenceCurve(source, binding)?.Length ?? 0)
                .FirstOrDefault();
            ObjectReferenceKeyframe[] sourceFrames =
                AnimationUtility.GetObjectReferenceCurve(source, sourceBinding) ??
                Array.Empty<ObjectReferenceKeyframe>();
            ObjectReferenceKeyframe[] visibleFrames = sourceFrames
                .Where(frame => frame.value is Sprite)
                .ToArray();
            if (visibleFrames.Length == 0)
                throw new InvalidOperationException($"No sprite frames were found in {source.name}.");

            float firstTime = visibleFrames[0].time;
            float frameDuration = 1f / Mathf.Max(1f, source.frameRate);
            var frames = new ObjectReferenceKeyframe[visibleFrames.Length + 1];
            for (int index = 0; index < visibleFrames.Length; index++)
            {
                frames[index] = new ObjectReferenceKeyframe
                {
                    time = visibleFrames[index].time - firstTime,
                    value = visibleFrames[index].value
                };
            }

            frames[^1] = new ObjectReferenceKeyframe
            {
                time = frames[^2].time + frameDuration,
                value = frames[^2].value
            };

            AnimationClip destination = LoadOrCreateClip(destinationPath);
            ClearClip(destination);
            destination.frameRate = source.frameRate;
            AnimationUtility.SetObjectReferenceCurve(destination, SpriteBinding(), frames);
            SetLooping(destination, loop);
            EditorUtility.SetDirty(destination);
            return destination;
        }

        private static AnimationClip CreateSingleSpriteClip(Sprite sprite, string destinationPath)
        {
            const float frameRate = 6f;
            AnimationClip destination = LoadOrCreateClip(destinationPath);
            ClearClip(destination);
            destination.frameRate = frameRate;
            AnimationUtility.SetObjectReferenceCurve(destination, SpriteBinding(), new[]
            {
                new ObjectReferenceKeyframe { time = 0f, value = sprite },
                new ObjectReferenceKeyframe { time = 1f / frameRate, value = sprite }
            });
            SetLooping(destination, true);
            EditorUtility.SetDirty(destination);
            return destination;
        }

        private static AnimationClip LoadOrCreateClip(string path)
        {
            AnimationClip clip = AssetDatabase.LoadAssetAtPath<AnimationClip>(path);
            if (clip != null)
                return clip;

            clip = new AnimationClip();
            AssetDatabase.CreateAsset(clip, path);
            return clip;
        }

        private static void ClearClip(AnimationClip clip)
        {
            foreach (EditorCurveBinding binding in AnimationUtility.GetObjectReferenceCurveBindings(clip))
                AnimationUtility.SetObjectReferenceCurve(clip, binding, null);
            foreach (EditorCurveBinding binding in AnimationUtility.GetCurveBindings(clip))
                AnimationUtility.SetEditorCurve(clip, binding, null);
        }

        private static EditorCurveBinding SpriteBinding()
        {
            return new EditorCurveBinding
            {
                path = string.Empty,
                type = typeof(SpriteRenderer),
                propertyName = "m_Sprite"
            };
        }

        private static void SetLooping(AnimationClip clip, bool loop)
        {
            AnimationClipSettings settings = AnimationUtility.GetAnimationClipSettings(clip);
            settings.loopTime = loop;
            AnimationUtility.SetAnimationClipSettings(clip, settings);
        }

        private static AnimatorController BuildController(
            string controllerPath,
            string idleName,
            AnimationClip idleClip,
            string attackName,
            AnimationClip attackClip)
        {
            AnimatorController controller = AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);
            if (controller == null)
                controller = AnimatorController.CreateAnimatorControllerAtPath(controllerPath);

            controller.parameters = Array.Empty<AnimatorControllerParameter>();
            controller.AddParameter(AttackParameter, AnimatorControllerParameterType.Trigger);

            AnimatorStateMachine stateMachine = controller.layers[0].stateMachine;
            foreach (ChildAnimatorState childState in stateMachine.states.ToArray())
                stateMachine.RemoveState(childState.state);

            AnimatorState idle = stateMachine.AddState(idleName, new Vector3(250f, 80f));
            idle.motion = idleClip;
            idle.writeDefaultValues = true;
            AnimatorState attack = stateMachine.AddState(attackName, new Vector3(520f, 80f));
            attack.motion = attackClip;
            attack.writeDefaultValues = true;
            stateMachine.defaultState = idle;

            AnimatorStateTransition attackTransition = idle.AddTransition(attack);
            attackTransition.hasExitTime = false;
            attackTransition.duration = 0.03f;
            attackTransition.AddCondition(AnimatorConditionMode.If, 0f, AttackParameter);

            AnimatorStateTransition returnTransition = attack.AddTransition(idle);
            returnTransition.hasExitTime = true;
            returnTransition.exitTime = 0.96f;
            returnTransition.duration = 0.04f;

            EditorUtility.SetDirty(controller);
            EditorUtility.SetDirty(stateMachine);
            return controller;
        }

        private static void ConfigurePrefab(
            string prefabPath,
            RuntimeAnimatorController controller,
            AnimationClip attackClip,
            float damageMoment,
            float recoverySeconds)
        {
            GameObject prefabRoot = PrefabUtility.LoadPrefabContents(prefabPath);
            try
            {
                SpriteRenderer visual = prefabRoot.GetComponentInChildren<SpriteRenderer>(true);
                if (visual == null)
                    throw new InvalidOperationException($"No SpriteRenderer was found in {prefabPath}.");

                Animator animator = visual.GetComponent<Animator>();
                if (animator == null)
                    animator = visual.gameObject.AddComponent<Animator>();
                animator.runtimeAnimatorController = controller;
                animator.applyRootMotion = false;
                animator.cullingMode = AnimatorCullingMode.AlwaysAnimate;

                MonoBehaviour attack = prefabRoot.GetComponents<MonoBehaviour>()
                    .FirstOrDefault(component => component != null &&
                        component.GetType().FullName == "SpookyGame.Enemies.EnemyMeleeAttack");
                if (attack == null)
                    throw new InvalidOperationException($"EnemyMeleeAttack was not found in {prefabPath}.");

                SerializedObject serializedAttack = new SerializedObject(attack);
                serializedAttack.FindProperty("_attackAnimationTrigger").stringValue = AttackParameter;
                serializedAttack.FindProperty("_damageWindup").floatValue =
                    Mathf.Max(0.05f, attackClip.length * damageMoment);
                SerializedProperty cooldown = serializedAttack.FindProperty("_attackCooldown");
                cooldown.floatValue = Mathf.Max(cooldown.floatValue, attackClip.length + recoverySeconds);
                serializedAttack.ApplyModifiedPropertiesWithoutUndo();

                PrefabUtility.SaveAsPrefabAsset(prefabRoot, prefabPath);
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(prefabRoot);
            }
        }
    }
}
